# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Locatodo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Locatodo

  target 'Locatodo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LocatodoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Locatodo-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Locatodo-tvOS
end
